# Singular Value Decomposition
Singular Value Decomposition adalah cara memecah suatu matriks menjadi tiga komponen utama. Misalkan ada matriks A berukuran 𝑚×𝑛, maka:


$$A=UΣV^T$$


- A: matriks asli
- 𝑈: matriks ortogonal berukuran 𝑚×𝑚, berisi vektor-vektor arah baris
- Σ: matriks diagonal 𝑚×𝑛 berisi singular values (nilai singular) dari A
- $𝑉^𝑇$: transpose dari matriks ortogonal 𝑉 berukuran 𝑛×𝑛



## Kegunaan svd
1. Reduksi Dimensi (Dimensionality Reduction)

SVD digunakan untuk menyederhanakan data berdimensi tinggi menjadi dimensi yang lebih rendah tanpa kehilangan informasi penting.Contoh:
- Dalam PCA (Principal Component Analysis), SVD digunakan untuk mengekstrak fitur penting dari data besar seperti gambar atau teks.
2. Penghapusan Derau (Noise Reduction)

Dengan membuang singular value kecil, kita bisa membersihkan data dari noise.
Contoh:
- Memperjelas citra yang kabur.
- Mengurangi noise pada data sinyal atau suara.
3. Kompresi Data dan Gambar

SVD dapat menyimpan representasi ringkas dari data besar, seperti gambar.
Contoh:
- Kompresi gambar JPG menggunakan pendekatan SVD untuk menyimpan gambar dengan ukuran lebih kecil tetapi kualitas tetap terjaga.
4. Rekomendasi Sistem (Recommendation Systems)

Digunakan dalam sistem rekomendasi seperti yang digunakan oleh Netflix atau Spotify.
Contoh:
- Matrix rating pengguna x film didekomposisi dengan SVD → digunakan untuk memprediksi rating film yang belum ditonton.
5. Natural Language Processing (NLP)

SVD digunakan dalam analisis teks seperti:
- Latent Semantic Analysis (LSA) untuk menemukan makna tersembunyi dalam kumpulan teks.

- Mendeteksi hubungan antar kata, dokumen, atau konsep.

### Bagaimana formula svd (Singular Value Decomposition)

Jika kita punya sebuah matriks
𝐴 berukuran 𝑚×𝑛, maka Singular Value Decomposition (SVD) memfaktorkan menjadi:


$$
A = U \Sigma V^T
$$


Penjelasan Setiap Komponen:
1. 𝐴 — Matriks asli

Ukuran: 𝑚×𝑛 Boleh persegi atau tidak (misalnya 3×2, 4×4, dll.)

2. 𝑈 — Matriks ortogonal kiri

Ukuran: 𝑚×𝑚 Berisi eigenvector dari $𝐴𝐴^𝑇$

Sifat:

$$U^TU=I_m$$


3. Σ — Matriks diagonal berisi singular value

Ukuran: 𝑚×𝑛 Diagonalnya berisi:


$$σ_1≥σ_2≥⋯≥σ_r>0$$


Nilai-nilai ini adalah akar dari eigenvalue $𝐴^𝑇𝐴$


4. V — Matriks ortogonal kanan

Ukuran: 𝑛×𝑛 Berisi eigenvector dari 𝐴^𝑇𝐴
Sifat:

$$𝑉^𝑇𝑉=𝐼_𝑛$$



Rumus Bentuk Matrik:

Jika 𝐴 adalah matriks 3×2, maka:



$$
A = U_{3 \times 3} \cdot \Sigma_{3 \times 2} \cdot V^T_{2 \times 2}$$


Bentuk visual:


$$
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} \\
a_{31} & a_{32}
\end{bmatrix}
=
\begin{bmatrix}
\uparrow & \uparrow & \uparrow \\
u_1 & u_2 & u_3 \\
\downarrow & \downarrow & \downarrow
\end{bmatrix}
\cdot
\begin{bmatrix}
\sigma_1 & 0 \\
0 & \sigma_2 \\
0 & 0
\end{bmatrix}
\cdot
\begin{bmatrix}
\leftarrow v_1^T \rightarrow \\
\leftarrow v_2^T \rightarrow
\end{bmatrix}
$$




### Code pembuktian

In [3]:
import numpy as np

# Matriks A dari soal
A = np.array([
    [3, 7],
    [2, 5],
    [4, 3],
    [1, 1]
], dtype=float)

# Langkah 1: Hitung A^T A
A_TA = A.T @ A
print("A^T A =\n", A_TA)

# Langkah 2: Hitung eigenvalue dan eigenvector A^T A
eigvals, eigvecs = np.linalg.eigh(A_TA)

# Urutkan dari terbesar ke terkecil
idx = np.argsort(eigvals)[::-1]
eigvals = eigvals[idx]
eigvecs = eigvecs[:, idx]

print("\nEigenvalues (A^T A) =", eigvals)
print("Eigenvectors (V) =\n", eigvecs)

# Langkah 3: Hitung singular value
singular_values = np.sqrt(eigvals)
print("\nSingular values =", singular_values)

# Bentuk Sigma (4x2 karena A 4x2)
Sigma = np.zeros((4, 2))
Sigma[0, 0] = singular_values[0]
Sigma[1, 1] = singular_values[1]
print("\nSigma =\n", Sigma)

# Langkah 4: Matriks V
V = eigvecs

# Langkah 5: Hitung U = (1/σ) * A * v
u1 = (A @ V[:, 0]) / singular_values[0]
u2 = (A @ V[:, 1]) / singular_values[1]

# Gabungkan jadi matriks U (4x2 untuk dua singular value)
U = np.column_stack((u1, u2))
print("\nU (2 kolom pertama) =\n", U)

# Langkah 6: Buktikan A = U Σ V^T
A_reconstructed = U @ Sigma[:2, :] @ V.T
print("\nA reconstructed =\n", A_reconstructed)

print("\nA original =\n", A)

# Hitung error rekonstruksi
error = np.linalg.norm(A - A_reconstructed)
print(f"\nReconstruction error = {error}")

A^T A =
 [[30. 44.]
 [44. 84.]]

Eigenvalues (A^T A) = [108.623638   5.376362]
Eigenvectors (V) =
 [[ 0.48835631 -0.87264432]
 [ 0.87264432  0.48835631]]

Singular values = [10.42226645  2.31869834]

Sigma =
 [[10.42226645  0.        ]
 [ 0.          2.31869834]
 [ 0.          0.        ]
 [ 0.          0.        ]]

U (2 kolom pertama) =
 [[ 0.72667296  0.34526321]
 [ 0.51235825  0.300381  ]
 [ 0.4386146  -0.87355405]
 [ 0.13058586 -0.16573437]]

A reconstructed =
 [[3. 7.]
 [2. 5.]
 [4. 3.]
 [1. 1.]]

A original =
 [[3. 7.]
 [2. 5.]
 [4. 3.]
 [1. 1.]]

Reconstruction error = 1.88411095042053e-15
